[project]
name = "ghost-coder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=3.3.1",
    "pyinput>=0.3.2",
    "pywebview>=6.1",
]
